# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d53e5ee7136a22b61d7b6c0464a6bd5102c99648a11b8528d639bd7e173f502e4aa6d96f17820ac9b8c9391588dea526d2f24f212ebf958b6af9c880fef6197

test:
  secret_key_base: a84b891e7c7ff55b5c075e6593f5cda005a89215c0af6cb71768a0387f2ea1ea59d7b727f9cd0b388a72d8e1e6827eaea9f8acdbbc3746b85dbd975d0fbb2cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
